// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeBid.Api.Data;

#nullable disable

namespace SafeBid.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004165254_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SafeBid.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuyerTier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("HealthScore")
                        .HasColumnType("int");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellerTier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SevereViolationCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BuyerTier = "Bronze",
                            CreatedAt = new DateTime(2026, 10, 4, 16, 52, 53, 642, DateTimeKind.Utc).AddTicks(2780),
                            Email = "admin@safebid.vn",
                            FullName = "Admin",
                            HealthScore = 100,
                            IsBanned = false,
                            Role = "Admin",
                            SellerTier = "Bronze",
                            SevereViolationCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BuyerTier = "Bronze",
                            CreatedAt = new DateTime(2026, 10, 4, 16, 52, 53, 642, DateTimeKind.Utc).AddTicks(3373),
                            Email = "user@safebid.vn",
                            FullName = "Normal User",
                            HealthScore = 100,
                            IsBanned = false,
                            Role = "User",
                            SellerTier = "Bronze",
                            SevereViolationCount = 0
                        });
                });

            modelBuilder.Entity("SafeBid.Api.Models.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AvailableBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HoldAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsConfiscated")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AvailableBalance = 0m,
                            HoldAmount = 0m,
                            IsConfiscated = false,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AvailableBalance = 100000m,
                            HoldAmount = 0m,
                            IsConfiscated = false,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("SafeBid.Api.Models.Wallet", b =>
                {
                    b.HasOne("SafeBid.Api.Models.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("SafeBid.Api.Models.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeBid.Api.Models.User", b =>
                {
                    b.Navigation("Wallet")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
